#!/bin/bash

# add all changes
git add .

# commit changes with provided message, or a default message if none is provided
if [ -z "$1" ]
then
  message="Update"
else
  message="$1"
fi
git commit -m "$message"

# push changes to remote repository
git push

